/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import java.time.LocalDate
import org.openapitools.client.core.ApiModel

case class ActivityUpdate (
  /* One of: call | email | meeting | task | note */
  activityType: Option[ActivityType] = None,
  /* User responsible (`employee.employee_id`). */
  assignedTo: Option[String] = None,
  /* Contact this activity belongs to (`contact.contact_id`). References the contact entity. */
  contactId: Option[String] = None,
  description: Option[String] = None,
  /* Follow-up / Wiedervorlage date. Open activities with a due date in the past are overdue. */
  dueDate: Option[LocalDate] = None,
  /* When to remind about the follow-up. */
  reminderDate: Option[LocalDate] = None,
  /* One of: open | done | cancelled */
  status: Option[ActivityStatus] = None,
  /* Short subject line. */
  subject: Option[String] = None
) extends ApiModel

object ActivityUpdateEnums {

}
