/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import java.time.OffsetDateTime
import java.util.UUID
import org.openapitools.client.core.ApiModel

case class ComplianceTraining (
  /* Whether HR can assign this training as required for employees. */
  assignable: Option[Boolean] = None,
  /* Stable code used by plugins and frontend players (e.g. \"data_privacy\"). */
  code: Option[String] = None,
  createdAt: Option[OffsetDateTime] = None,
  deletedAt: Option[OffsetDateTime] = None,
  description: Option[String] = None,
  id: Option[UUID] = None,
  /* Minimum score (0–100) required to pass. */
  passScore: Option[Int] = None,
  /* Marketplace plugin platform id when source = Plugin. */
  pluginPlatform: Option[String] = None,
  source: Option[TrainingSource] = None,
  tenantId: Option[UUID] = None,
  title: Option[String] = None,
  updatedAt: Option[OffsetDateTime] = None,
  /* Certificate validity in months; null = no expiry. */
  validityMonths: Option[Int] = None
) extends ApiModel

object ComplianceTrainingEnums {

}
