/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import java.time.LocalDate
import java.time.OffsetDateTime
import org.openapitools.client.core.ApiModel

case class ContactUpdate (
  accountHolder: Option[String] = None,
  acquisitionCost: Option[String] = None,
  addressSupplement: Option[String] = None,
  attention: Option[String] = None,
  bankName: Option[String] = None,
  bic: Option[String] = None,
  buyerReference: Option[String] = None,
  category: Option[String] = None,
  certificateAuthority: Option[String] = None,
  certificateNumber: Option[String] = None,
  certificateParagraph: Option[String] = None,
  certificateValidUntil: Option[LocalDate] = None,
  city: Option[String] = None,
  companyName: Option[String] = None,
  contactPersons: Option[AnyType] = None,
  contactType: Option[ContactType] = None,
  country: Option[CountryCode] = None,
  creditLimit: Option[String] = None,
  creditorAccountSkr03: Option[String] = None,
  creditorAccountSkr04: Option[String] = None,
  currency: Option[String] = None,
  customFields: Option[AnyType] = None,
  customerNumber: Option[String] = None,
  debitorAccountSkr03: Option[String] = None,
  debitorAccountSkr04: Option[String] = None,
  defaultDebitorNumber: Option[String] = None,
  deliveryBlock: Option[Boolean] = None,
  department: Option[String] = None,
  discountDays: Option[Int] = None,
  discountPercentage: Option[String] = None,
  donationReceiptEligible: Option[Boolean] = None,
  email: Option[String] = None,
  externalId: Option[String] = None,
  fax: Option[String] = None,
  iban: Option[String] = None,
  industry: Option[String] = None,
  isActive: Option[Boolean] = None,
  isMember: Option[Boolean] = None,
  isNonprofit: Option[Boolean] = None,
  lastContactDate: Option[LocalDate] = None,
  lastPurchaseDate: Option[LocalDate] = None,
  leitwegId: Option[String] = None,
  lifetimeValue: Option[String] = None,
  mandateDate: Option[LocalDate] = None,
  mandateReference: Option[String] = None,
  marketingConsent: Option[Boolean] = None,
  marketingConsentAt: Option[OffsetDateTime] = None,
  marketingConsentSource: Option[String] = None,
  mobile: Option[String] = None,
  name: Option[String] = None,
  nextContactDate: Option[LocalDate] = None,
  notes: Option[String] = None,
  openingBalance: Option[String] = None,
  openingBalanceDate: Option[LocalDate] = None,
  orderReference: Option[String] = None,
  paymentBlock: Option[Boolean] = None,
  paymentGracePeriodDays: Option[Int] = None,
  paymentMethods: Option[Seq[String]] = None,
  paymentTerms: Option[String] = None,
  phone: Option[String] = None,
  rating: Option[Int] = None,
  salesRepresentative: Option[String] = None,
  sepaBatchBooking: Option[Boolean] = None,
  sepaSequenceType: Option[SepaSequenceType] = None,
  socialMedia: Option[AnyType] = None,
  source: Option[String] = None,
  state: Option[String] = None,
  street: Option[String] = None,
  streetNumber: Option[String] = None,
  supplierNumber: Option[String] = None,
  tags: Option[Seq[String]] = None,
  taxCountry: Option[CountryCode] = None,
  taxNumber: Option[String] = None,
  taxOffice: Option[String] = None,
  totalInvoices: Option[Int] = None,
  totalRevenue: Option[String] = None,
  vatId: Option[String] = None,
  vatIdValidated: Option[Boolean] = None,
  vatIdValidationDate: Option[LocalDate] = None,
  website: Option[String] = None,
  zip: Option[String] = None
) extends ApiModel

object ContactUpdateEnums {

}
