/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import java.time.OffsetDateTime
import org.openapitools.client.core.ApiModel

case class CustomerCommunicationCreate (
  /* The message body, call summary or note text. */
  body: Option[String] = None,
  channel: CommunicationChannel,
  /* The contact (customer/supplier) this communication belongs to. References the contact entity. */
  contactId: String,
  /* Email/phone of the counterparty, if applicable. */
  counterparty: Option[String] = None,
  direction: CommunicationDirection,
  /* When the communication happened (defaults to now on create). */
  occurredAt: Option[OffsetDateTime] = None,
  subject: Option[String] = None,
  /* Free-form tags, e.g. `[\"follow-up-required\"]`. */
  tags: Option[AnyType] = None
) extends ApiModel

object CustomerCommunicationCreateEnums {

}
