/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import java.time.LocalDate
import org.openapitools.client.core.ApiModel

case class DeliveryDate (
  /* References the customer entity. */
  customerId: Option[String] = None,
  /* Date actually delivered (set on fulfillment). */
  fulfilledDate: Option[LocalDate] = None,
  note: Option[String] = None,
  /* Sales order number (`order.order_number`). */
  orderNumber: String,
  /* Original date promised before rescheduling. */
  originalDate: Option[LocalDate] = None,
  /* Product line item this date applies to, if per-item. References the product entity. */
  productId: Option[String] = None,
  /* Date promised to the customer. */
  promisedDate: LocalDate,
  /* One of: promised | confirmed | rescheduled | fulfilled | late | cancelled */
  status: DeliveryDateStatus
) extends ApiModel

object DeliveryDateEnums {

}
