/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel

case class EmailTemplateUpdate (
  /* E-mail body with optional placeholders. */
  body: Option[String] = None,
  /* Human-readable template name, e.g. \"Follow-up after quote\". */
  name: Option[String] = None,
  /* One of: active | inactive */
  status: Option[EmailTemplateStatus] = None,
  /* E-mail subject line with optional placeholders. */
  subject: Option[String] = None,
  /* Placeholders used by this template, e.g. `[\"contact.first_name\"]`. */
  variables: Option[AnyType] = None
) extends ApiModel

object EmailTemplateUpdateEnums {

}
