/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel

case class EmissionsReport (
  byCategory: Seq[CategoryTotal],
  byScope: Seq[ScopeTotal],
  byYear: Seq[YearTotal],
  dataQuality: DataQuality,
  intensityPerEmployee: Option[Double] = None,
  /* tCO2e per million EUR net revenue. */
  intensityPerRevenueMio: Option[Double] = None,
  /* Sum of paid/sent/partially-paid invoices (EUR net) in the year. */
  netRevenue: Option[Double] = None,
  /* Spend-based estimate from bookkeeping payments (EXIOBASE factor). */
  spendBasedEstimateTco2e: Option[Double] = None,
  targets: Seq[TargetProgress],
  totalTco2e: String
) extends ApiModel

