/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import java.time.OffsetDateTime
import org.openapitools.client.core.ApiModel

case class EmissionEntry (
  /* Activity amount in `unit` (kWh, l, km, t, tkm, EUR). */
  activityValue: String,
  /* GHG-Protocol category key, e.g. \"purchased_goods\", \"business_travel\". */
  categoryId: String,
  description: String,
  /* Emission-factor source, e.g. \"UBA-2024\", \"DEFRA-2024\". */
  efSource: String,
  efVersion: String,
  /* \"activity\" | \"spend\" | \"supplier\". */
  method: EmissionMethod,
  /* GHG scope: \"1\" | \"2\" | \"3\". */
  scope: GhgScope,
  /* Computed server-side: activity * factor / 1000, rounded to 4 dp. */
  tco2e: String,
  /* Unit of the activity value. */
  unit: String,
  updatedAt: Option[OffsetDateTime] = None,
  /* Reporting year. */
  year: Int
) extends ApiModel

object EmissionEntryEnums {

}
