/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel

case class GroupFigure (
  /* Bilanzsumme in EUR (§ 293 Abs. 1 Nr. 1 HGB). */
  bilanzsumme: Option[String] = None,
  /* § 291-Befreiung in Anspruch genommen. */
  exemptionClaimed: Option[Boolean] = None,
  /* Durchschnittliche Arbeitnehmerzahl (§ 293 Abs. 1 Nr. 3 HGB). */
  mitarbeiter: Option[Long] = None,
  /* Netto-Umsatzerlöse in EUR (§ 293 Abs. 1 Nr. 2 HGB). */
  nettoUmsatz: Option[String] = None,
  /* Name des Mutterunternehmens (§ 291 HGB, Zwischenholding). */
  parentName: Option[String] = None,
  /* Sitz des Mutterunternehmens, z. B. \"EU/EWR\" (§ 291 HGB). */
  parentSitus: Option[String] = None,
  year: Int
) extends ApiModel

