/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import java.time.LocalDate
import java.time.OffsetDateTime
import java.util.UUID
import org.openapitools.client.core.ApiModel

case class Invoice (
  attachments: Option[AnyType] = None,
  billingPeriodEnd: Option[LocalDate] = None,
  billingPeriodStart: Option[LocalDate] = None,
  cancellationDate: Option[LocalDate] = None,
  /* References the invoice entity. */
  cancellationInvoiceId: Option[String] = None,
  cancellationReason: Option[String] = None,
  /* References the contract entity. */
  contractId: Option[UUID] = None,
  currency: CurrencyCode,
  /* References the customer entity. */
  customerId: Option[String] = None,
  discountAmount: Option[String] = None,
  discountDays: Option[Int] = None,
  discountPercentage: Option[String] = None,
  documentType: Option[DocumentType] = None,
  dunningLevel: Option[Int] = None,
  inputVatAmount: Option[String] = None,
  inputVatDeductible: Option[Boolean] = None,
  inputVatPercentage: Option[String] = None,
  introductionText: Option[String] = None,
  invoiceType: InvoiceType,
  isCancelled: Option[Boolean] = None,
  isDraft: Option[Boolean] = None,
  isEuAcquisition: Option[Boolean] = None,
  isEuDelivery: Option[Boolean] = None,
  isIntraCommunityAcquisition: Option[Boolean] = None,
  isReverseCharge: Option[Boolean] = None,
  issueDate: LocalDate,
  ledgerAccount: Option[String] = None,
  lineItems: AnyType,
  margin25a: Option[Boolean] = None,
  margin25aGross: Option[String] = None,
  margin25aPurchasePrice: Option[String] = None,
  notes: Option[String] = None,
  orderNumber: Option[String] = None,
  originalPdfPath: Option[String] = None,
  paidAmount: Option[String] = None,
  paymentDueDate: Option[LocalDate] = None,
  paymentStatus: Option[PaymentStatus] = None,
  paymentTermsText: Option[String] = None,
  /* References the preceding sales voucher entity. */
  precedingSalesVoucherId: Option[String] = None,
  precedingSalesVoucherType: Option[PrecedingSalesVoucherType] = None,
  receiptConfirmationAvailable: Option[Boolean] = None,
  /* References the invoice entity. */
  relatedInvoiceId: Option[UUID] = None,
  relationshipType: Option[String] = None,
  senderSnapshot: Option[AnyType] = None,
  sentAt: Option[OffsetDateTime] = None,
  servicePeriodEnd: Option[LocalDate] = None,
  servicePeriodStart: Option[LocalDate] = None,
  status: InvoiceStatus,
  subtotal: String,
  /* References the supplier entity. */
  supplierId: Option[String] = None,
  taxExemptionReason: Option[String] = None,
  totalAmount: String,
  totalTax: String,
  vatCountry: Option[CountryCode] = None,
  vatSpecialCase: Option[String] = None
) extends ApiModel

object InvoiceEnums {

}
