/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import java.time.LocalDate
import org.openapitools.client.core.ApiModel

case class KycRecordUpdate (
  /* Referenz auf den Kunden/Kontakt. */
  customerId: Option[String] = None,
  /* Name des Kunden (für die Suche). */
  customerName: Option[String] = None,
  /* Datum der KYC-Prüfung (GwG § 8). */
  kycDate: Option[LocalDate] = None,
  /* Freitext-Notizen. */
  notes: Option[String] = None,
  /* Aufbewahrungsfrist (GwG § 8 Abs. 4: 5 Jahre). */
  retentionUntil: Option[LocalDate] = None,
  /* Risikoeinschätzung (z. B. Risikoklasse). */
  riskAssessment: Option[String] = None
) extends ApiModel

