/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import java.time.OffsetDateTime
import java.util.UUID
import org.openapitools.client.core.ApiModel

case class Model (
  backupCodes: Seq[String],
  createdAt: OffsetDateTime,
  deletedAt: Option[OffsetDateTime] = None,
  email: String,
  emailVerified: Boolean,
  id: UUID,
  isActive: Boolean,
  isTotpEnabled: Boolean,
  lastLogin: Option[OffsetDateTime] = None,
  name: String,
  oauthId: Option[String] = None,
  oauthProvider: Option[String] = None,
  /* Set on password change; auth/refresh tokens issued before this timestamp are rejected by the auth middleware. */
  passwordChangedAt: Option[OffsetDateTime] = None,
  passwordHash: String,
  picture: Option[String] = None,
  /* When the user accepted the data privacy policy (GDPR consent record). */
  privacyAcceptedAt: Option[OffsetDateTime] = None,
  totpSecret: Option[String] = None,
  updatedAt: OffsetDateTime
) extends ApiModel

