/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import java.time.LocalDate
import org.openapitools.client.core.ApiModel

case class OrderConfirmationCreate (
  address: Option[AnyType] = None,
  confirmationNumber: Option[String] = None,
  /* References the contact entity. */
  contactId: Option[String] = None,
  contactName: Option[String] = None,
  currency: String,
  files: Option[AnyType] = None,
  introduction: Option[String] = None,
  lineItems: Option[AnyType] = None,
  /* References the preceding sales voucher entity. */
  precedingSalesVoucherId: Option[String] = None,
  precedingSalesVoucherType: Option[PrecedingSalesVoucherType] = None,
  remark: Option[String] = None,
  taxCondition: Option[String] = None,
  title: Option[String] = None,
  voucherDate: LocalDate,
  voucherStatus: VoucherStatus
) extends ApiModel

object OrderConfirmationCreateEnums {

}
