/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel

case class OrderUpdate (
  auditLog: Option[AnyType] = None,
  currency: Option[String] = None,
  /* References the customer entity. */
  customerId: Option[String] = None,
  externalReference: Option[String] = None,
  invoiceAddress: Option[AnyType] = None,
  items: Option[AnyType] = None,
  language: Option[LanguageCode] = None,
  orderStatus: Option[OrderStatus] = None,
  paymentMethod: Option[PaymentMethod] = None,
  shippingAddress: Option[AnyType] = None,
  shippingCost: Option[String] = None,
  shippingMethod: Option[String] = None,
  shippingWeight: Option[String] = None,
  tags: Option[Seq[String]] = None,
  totalCost: Option[String] = None
) extends ApiModel

object OrderUpdateEnums {

}
