/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import java.time.LocalDate
import org.openapitools.client.core.ApiModel

case class ParticipationUpdate (
  /* Datum des Erwerbs der Beteiligung. */
  acquiredAt: Option[LocalDate] = None,
  /* Bestellungsrecht für Geschäftsführung/Aufsichtsrat (§ 290 Abs. 2 Nr. 2 HGB). */
  boardAppointment: Option[Boolean] = None,
  /* Name des Beteiligungsunternehmens (§ 271 HGB). */
  companyName: Option[String] = None,
  /* Beherrschungsvertrag (§ 290 Abs. 2 Nr. 3 HGB). */
  controlAgreement: Option[Boolean] = None,
  /* Rechtsform, z. B. \"GmbH\". */
  legalForm: Option[String] = None,
  /* Anteilsquote in Prozent (§ 271 HGB; > 20 % widerlegbare Vermutung). */
  ownershipPct: Option[String] = None,
  /* Zweckgesellschaft (§ 290 Abs. 2 Nr. 4 HGB). */
  purposeVehicle: Option[Boolean] = None,
  /* Stimmrechtsmehrheit (§ 290 Abs. 2 Nr. 1 HGB). */
  votingMajority: Option[Boolean] = None
) extends ApiModel

