/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import java.time.OffsetDateTime
import org.openapitools.client.core.ApiModel

case class PostingCategoryUpdate (
  accountNumber: Option[String] = None,
  accountNumberSkr03: Option[String] = None,
  accountNumberSkr04: Option[String] = None,
  accountNumberSkr49: Option[String] = None,
  categoryType: Option[PostingCategoryType] = None,
  createdAt: Option[OffsetDateTime] = None,
  defaultVatRate: Option[Int] = None,
  description: Option[String] = None,
  eksCategory: Option[String] = None,
  euVatLine: Option[Int] = None,
  inputVatPercentage: Option[String] = None,
  isActive: Option[Boolean] = None,
  isSystem: Option[Boolean] = None,
  name: Option[String] = None,
  skrVersion: Option[String] = None,
  updatedAt: Option[OffsetDateTime] = None,
  userModifiedSkr03: Option[Boolean] = None,
  userModifiedSkr04: Option[Boolean] = None
) extends ApiModel

object PostingCategoryUpdateEnums {

}
