/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import java.util.UUID
import org.openapitools.client.core.ApiModel

case class PriceTierCreate (
  /* None = tier applies to all customers; otherwise a customer group id. */
  customerGroupId: Option[String] = None,
  /* Quantity from which this tier applies (inclusive). */
  minQuantity: Option[Long] = None,
  /* References the product entity. */
  productId: UUID,
  /* Net unit price once `min_quantity` is reached. */
  unitPrice: String
) extends ApiModel

