/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import java.time.LocalDate
import java.util.UUID
import org.openapitools.client.core.ApiModel

case class ProductionOrder (
  /* References the BOM entity. */
  bomId: Option[UUID] = None,
  /* JSON snapshot of the BOM components at creation time. */
  components: Option[AnyType] = None,
  endDate: Option[LocalDate] = None,
  notes: Option[String] = None,
  orderNumber: String,
  /* The finished product to manufacture. References the product entity. */
  productId: UUID,
  /* Quantity of finished product to produce. */
  quantity: Long,
  /* Warehouse components are consumed from. References the warehouse entity. */
  sourceWarehouseId: Option[String] = None,
  startDate: Option[LocalDate] = None,
  /* One of: planned | in_production | completed | cancelled */
  status: Option[ProductionOrderStatus] = None,
  /* Warehouse the finished product is added to. References the warehouse entity. */
  targetWarehouseId: Option[String] = None
) extends ApiModel

object ProductionOrderEnums {

}
