/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import java.util.UUID
import org.openapitools.client.core.ApiModel

case class ProductCreate (
  availability: Option[String] = None,
  barcode: Option[String] = None,
  brand: Option[String] = None,
  categoryId: Option[String] = None,
  condition: Option[String] = None,
  defaultLedgerAccount: Option[String] = None,
  defaultPrice: Option[String] = None,
  /* References the price formula entity. */
  defaultPriceFormulaId: Option[UUID] = None,
  defaultTaxRate: Option[String] = None,
  description: Option[String] = None,
  gtin: Option[String] = None,
  height: Option[String] = None,
  imageLink: Option[String] = None,
  images: Option[AnyType] = None,
  isTaxable: Option[Boolean] = None,
  length: Option[String] = None,
  link: Option[String] = None,
  /* Target stock level used by reorder proposals. */
  maxStock: Option[Long] = None,
  /* Reorder point — when stock falls below this, a reorder is suggested. */
  minStock: Option[Long] = None,
  mpn: Option[String] = None,
  name: String,
  packageHeight: Option[String] = None,
  packageLength: Option[String] = None,
  packageWeightUnit: Option[String] = None,
  packageWeightValue: Option[String] = None,
  packageWidth: Option[String] = None,
  productCode: String,
  productType: Option[String] = None,
  purchasePrice: Option[String] = None,
  /* Suggested purchase quantity when a reorder proposal is created. */
  reorderQuantity: Option[Long] = None,
  salePrice: Option[String] = None,
  shippingPrice: Option[String] = None,
  shippingRequiresInsurance: Option[Boolean] = None,
  sku: String,
  stockQuantity: Option[Long] = None,
  tags: Option[AnyType] = None,
  taxPrice: Option[String] = None,
  /* Whether this product requires batch (Chargennummer) tracking. */
  trackBatch: Option[Boolean] = None,
  /* Whether this product requires serial-number tracking. */
  trackSerial: Option[Boolean] = None,
  unit: Option[AnyType] = None,
  weightUnit: Option[String] = None,
  weightValue: Option[String] = None,
  width: Option[String] = None
) extends ApiModel

