/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import java.util.UUID
import org.openapitools.client.core.ApiModel

case class ProductAttributeUpdate (
  /* Whether this attribute participates in the shop's faceted filters. */
  isFilterable: Option[Boolean] = None,
  /* Attribute name, e.g. `Material`, `Farbe`, `Gewicht`. */
  name: Option[String] = None,
  /* Ordering position within the product's attribute list. */
  position: Option[Int] = None,
  /* The product this attribute belongs to. References the product entity. */
  productId: Option[UUID] = None,
  /* Optional unit of measure for numeric attributes, e.g. `g`, `cm`. */
  unit: Option[String] = None,
  /* Attribute value, e.g. `Baumwolle`, `Rot`, `180g`. */
  value: Option[String] = None
) extends ApiModel

