/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import java.time.LocalDate
import java.time.OffsetDateTime
import org.openapitools.client.core.ApiModel

case class ProformaInvoiceCreate (
  convertedAt: Option[OffsetDateTime] = None,
  /* Set when the proforma was converted into a real invoice. References the invoice entity. */
  convertedToInvoiceId: Option[String] = None,
  currency: CurrencyCode,
  /* References the customer entity. */
  customerId: Option[String] = None,
  /* Snapshot of the recipient at issue time (address, VAT id, …). */
  customerSnapshot: Option[AnyType] = None,
  issueDate: LocalDate,
  lineItems: AnyType,
  notes: Option[String] = None,
  /* Reference to the order/quote this proforma belongs to. */
  orderNumber: Option[String] = None,
  /* Optional deadline the real invoice should carry after conversion. */
  paymentDueDate: Option[LocalDate] = None,
  /* References the quotation entity. */
  quotationId: Option[String] = None,
  /* `draft` | `sent` | `converted`. */
  status: ProformaInvoiceStatus,
  subtotal: String,
  totalAmount: String,
  totalTax: String
) extends ApiModel

object ProformaInvoiceCreateEnums {

}
