/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import java.time.LocalDate
import org.openapitools.client.core.ApiModel

case class ShareholderUpdate (
  /* Anschrift des Aktionärs (§ 67 Abs. 1 AktG). */
  address: Option[String] = None,
  /* Geburtsdatum des Aktionärs (§ 67 Abs. 1 AktG). */
  birthDate: Option[LocalDate] = None,
  /* Elektronische Adresse (E-Mail) für die Kommunikation der Gesellschaft. */
  email: Option[String] = None,
  /* Vorname des Aktionärs (§ 67 Abs. 1 AktG). */
  firstName: Option[String] = None,
  /* Nachname des Aktionärs (§ 67 Abs. 1 AktG). */
  lastName: Option[String] = None,
  /* Aktiennummer bzw. Sammelurkunde (bei Nennbetragsaktien). */
  shareNumber: Option[String] = None,
  /* Stückzahl der gehaltenen Stückaktien (§ 67 Abs. 1 AktG). */
  shares: Option[String] = None
) extends ApiModel

