/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel

case class ShippingRuleUpdate (
  /* Provider that auto-filled this rule (e.g. \"ups\"), if any. */
  carrier: Option[String] = None,
  /* None = applies to all countries. */
  country: Option[CountryCode] = None,
  /* Delivery time text, e.g. \"1-3\". */
  deliveryTime: Option[String] = None,
  isActive: Option[Boolean] = None,
  maxWeightKg: Option[Double] = None,
  minWeightKg: Option[Double] = None,
  /* Delivery-method label, e.g. \"Standardversand\". */
  name: Option[String] = None,
  notes: Option[String] = None,
  /* Shipping cost in the shop's currency. */
  price: Option[String] = None,
  /* Lower wins when multiple rules match. */
  priority: Option[Int] = None
) extends ApiModel

object ShippingRuleUpdateEnums {

}
