/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import java.time.LocalDate
import org.openapitools.client.core.ApiModel

case class SilentPartner (
  /* Datum des Vertragsabschlusses. */
  contractDate: Option[LocalDate] = None,
  /* Einlage (§ 230 HGB). */
  einlage: Option[String] = None,
  /* Gewinnbeteiligungsquote in Prozent (§ 231 HGB). */
  gewinnquotePct: Option[String] = None,
  /* Nicht erhobene Gewinne (§ 232 Abs. 3 HGB). */
  gewinnvortrag: Option[String] = None,
  /* Instrument: \"typisch\" | \"atypisch\" | \"partiarisches_darlehen\" | \"genussrecht\". */
  instrumentType: InstrumentType,
  /* 25 % Kapitalertragsteuer einbehalten (§ 43 Abs. 1 Nr. 3 EStG; typisch + partiarisches Darlehen). */
  kestPflichtig: Option[Boolean] = None,
  /* Name des stillen Gesellschafters. */
  name: Option[String] = None,
  /* Freitext-Notizen. */
  notes: Option[String] = None,
  /* Kumulierte Verluste gegen die Einlage (§ 232 Abs. 2 HGB, ≤ Einlage). */
  verlustVerrechnungskonto: Option[String] = None,
  /* Verlustbeteiligung (§ 231 Abs. 2 HGB; kann ausgeschlossen werden). */
  verlustbeteiligung: Option[Boolean] = None
) extends ApiModel

object SilentPartnerEnums {

}
