/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel

case class SupplierConditionCreate (
  /* Currency for the minimum order value. */
  currency: String,
  /* Incoterms, e.g. \"EXW\", \"DAP\". */
  deliveryTerms: Option[String] = None,
  /* Early-payment discount percentage (Skonto), e.g. 2.0. */
  earlyPaymentDiscountPercent: Option[String] = None,
  /* Is this the default condition for the supplier? */
  isDefault: Option[Boolean] = None,
  /* Minimum order value required for this supplier. */
  minimumOrderValue: Option[String] = None,
  notes: Option[String] = None,
  /* Number of days within which payment is due. */
  paymentDueDays: Option[Int] = None,
  /* Payment terms, e.g. \"14 Tage, 2% Skonto\". */
  paymentTerms: Option[String] = None,
  /* The supplier this condition applies to (`contact_id`). References the supplier entity. */
  supplierContactId: String,
  /* The name of the supplier, denormalized for easy listing. */
  supplierName: Option[String] = None,
  /* Tiered discounts: JSON array of `{min_quantity, discount_percent}`. */
  volumeDiscountTiers: Option[AnyType] = None
) extends ApiModel

