/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import java.time.OffsetDateTime
import java.util.UUID
import org.openapitools.client.core.ApiModel

case class SupportTicketUpdate (
  assignedTo: Option[UUID] = None,
  channelId: Option[UUID] = None,
  channelType: Option[SupportChannelType] = None,
  closedAt: Option[OffsetDateTime] = None,
  createdAt: Option[OffsetDateTime] = None,
  customerEmail: Option[String] = None,
  /* References the customer entity. */
  customerId: Option[String] = None,
  customerName: Option[String] = None,
  externalId: Option[String] = None,
  firstMessageAt: Option[OffsetDateTime] = None,
  lastMessageAt: Option[OffsetDateTime] = None,
  /* References the lead entity. */
  leadId: Option[UUID] = None,
  messageCount: Option[Int] = None,
  orderRef: Option[String] = None,
  priority: Option[TicketPriority] = None,
  resolution: Option[String] = None,
  status: Option[SupportTicketStatus] = None,
  subject: Option[String] = None,
  tags: Option[AnyType] = None,
  tenantId: Option[UUID] = None,
  updatedAt: Option[OffsetDateTime] = None
) extends ApiModel

object SupportTicketUpdateEnums {

}
