/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import java.time.LocalDate
import org.openapitools.client.core.ApiModel

case class SupplierInvoiceUpdate (
  currency: Option[String] = None,
  /* References the goods receipt entity. */
  goodsReceiptId: Option[String] = None,
  invoiceDate: Option[LocalDate] = None,
  invoiceNumber: Option[String] = None,
  /* JSON array of `{product_id, name, quantity, unitPriceNet, taxRate}`. */
  lineItems: Option[AnyType] = None,
  notes: Option[String] = None,
  /* References the purchase order entity. */
  purchaseOrderId: Option[String] = None,
  /* One of: draft | matched | has_variances | posted | cancelled */
  status: Option[SupplierInvoiceStatus] = None,
  /* References the supplier entity. */
  supplierContactId: Option[String] = None,
  supplierName: Option[String] = None,
  totalGrossAmount: Option[String] = None,
  totalNetAmount: Option[String] = None
) extends ApiModel

object SupplierInvoiceUpdateEnums {

}
