/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import java.time.LocalDate
import org.openapitools.client.core.ApiModel

case class VoucherCreate (
  categoryId: Option[String] = None,
  /* References the contact entity. */
  contactId: Option[String] = None,
  contactName: Option[String] = None,
  currency: String,
  description: Option[String] = None,
  fileAttachments: Option[AnyType] = None,
  lineItems: Option[AnyType] = None,
  metadata: Option[AnyType] = None,
  notes: Option[String] = None,
  openAmount: Option[String] = None,
  paidDate: Option[LocalDate] = None,
  paymentStatus: Option[PaymentStatus] = None,
  taxAmounts: Option[AnyType] = None,
  taxCondition: Option[String] = None,
  totalGrossAmount: Option[String] = None,
  totalNetAmount: Option[String] = None,
  voucherDate: LocalDate,
  voucherNumber: Option[String] = None,
  voucherStatus: VoucherStatus,
  voucherType: VoucherType
) extends ApiModel

object VoucherCreateEnums {

}
