/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel

case class WebhookEvent (
  attempts: Option[Int] = None,
  /* source for inbound, target URL for outbound. */
  channel: Option[String] = None,
  /* inbound | outbound */
  direction: WebhookDirection,
  eventType: String,
  lastError: Option[String] = None,
  payload: Option[AnyType] = None,
  /* accepted | delivered | failed */
  status: Option[WebhookEventStatus] = None
) extends ApiModel

object WebhookEventEnums {

}
