/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.api

import org.openapitools.client.model._
import org.json4s._
import scala.reflect.ClassTag

object EnumsSerializers {

  def all: Seq[Serializer[_]] = Seq[Serializer[_]]() :+
    new EnumNameSerializer(ConfigFieldKindEnums.`Type`) :+
    new EnumNameSerializer(ConfigFieldKindOneOfEnums.`Type`) :+
    new EnumNameSerializer(ConfigFieldKindOneOf1Enums.`Type`) :+
    new EnumNameSerializer(ConfigFieldKindOneOf2Enums.`Type`) :+
    new EnumNameSerializer(ConfigFieldKindOneOf3Enums.`Type`) :+
    new EnumNameSerializer(ConfigFieldKindOneOf4Enums.`Type`) :+
    new EnumNameSerializer(PluginPricingEnums.`Type`) :+
    new EnumNameSerializer(PluginPricingOneOfEnums.`Type`) :+
    new EnumNameSerializer(PluginPricingOneOf1Enums.`Type`) :+
    new EnumNameSerializer(PluginPricingOneOf2Enums.`Type`)

  private class EnumNameSerializer[E <: Enumeration: ClassTag](enum: E)
    extends Serializer[E#Value] {
    import JsonDSL._

    val EnumerationClass: Class[E#Value] = classOf[E#Value]

    def deserialize(implicit format: Formats):
    PartialFunction[(TypeInfo, JValue), E#Value] = {
      case (t @ TypeInfo(EnumerationClass, _), json) if isValid(json) =>
        json match {
          case JString(value) =>
            enum.withName(value)
          case value =>
            throw new MappingException(s"Can't convert $value to $EnumerationClass")
        }
    }

    private[this] def isValid(json: JValue) = json match {
      case JString(value) if enum.values.exists(_.toString == value) => true
      case _ => false
    }

    def serialize(implicit format: Formats): PartialFunction[Any, JValue] = {
      case i: E#Value => i.toString
    }
  }

}
