/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.api

import org.openapitools.client.model.CreateConnectionRequest
import org.openapitools.client.model.MarketplaceConnection
import org.openapitools.client.model.OAuthAuthorizeRequest
import org.openapitools.client.model.OAuthAuthorizeResponse
import org.openapitools.client.model.OAuthCallbackRequest
import org.openapitools.client.model.PlatformInfo
import org.openapitools.client.model.SyncLog
import org.openapitools.client.model.SyncSummary
import org.openapitools.client.model.UpdateConnectionRequest
import org.openapitools.client.model.UpdateSyncDirectionRequest
import org.openapitools.client.core._
import org.openapitools.client.core.CollectionFormats._
import org.openapitools.client.core.ApiKeyLocations._

object MarketplaceApiApi {

  def apply(baseUrl: String = "https://demo.simplebilly.com") = new MarketplaceApiApi(baseUrl)
}

class MarketplaceApiApi(baseUrl: String) {

  /**
   * Expected answers:
   *   code 201 : MarketplaceConnection (Created)
   * 
   * Available security schemes:
   *   bearer_token (http)
   * 
   * @param createConnectionRequest 
   */
  def createConnectionApi(createConnectionRequest: CreateConnectionRequest)(implicit bearerToken: BearerToken): ApiRequest[MarketplaceConnection] =
    ApiRequest[MarketplaceConnection](ApiMethods.POST, baseUrl, "/api/v1/marketplace/connections", "application/json")
      .withCredentials(bearerToken).withBody(createConnectionRequest)
      .withSuccessResponse[MarketplaceConnection](201)
      

  /**
   * Expected answers:
   *   code 204 :  (Deleted)
   * 
   * Available security schemes:
   *   bearer_token (http)
   * 
   * @param connectionId 
   */
  def deleteConnectionApi(connectionId: String)(implicit bearerToken: BearerToken): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.DELETE, baseUrl, "/api/v1/marketplace/connections/{connection_id}", "application/json")
      .withCredentials(bearerToken).withPathParam("connection_id", connectionId)
      .withSuccessResponse[Unit](204)
      

  /**
   * Expected answers:
   *   code 200 : MarketplaceConnection (Connection details)
   * 
   * Available security schemes:
   *   bearer_token (http)
   * 
   * @param connectionId 
   */
  def getConnectionApi(connectionId: String)(implicit bearerToken: BearerToken): ApiRequest[MarketplaceConnection] =
    ApiRequest[MarketplaceConnection](ApiMethods.GET, baseUrl, "/api/v1/marketplace/connections/{connection_id}", "application/json")
      .withCredentials(bearerToken).withPathParam("connection_id", connectionId)
      .withSuccessResponse[MarketplaceConnection](200)
      

  /**
   * Expected answers:
   *   code 200 :  (Current sync directions)
   * 
   * Available security schemes:
   *   bearer_token (http)
   * 
   * @param connectionId 
   */
  def getSyncDirectionApi(connectionId: String)(implicit bearerToken: BearerToken): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.GET, baseUrl, "/api/v1/marketplace/connections/{connection_id}/directions", "application/json")
      .withCredentials(bearerToken).withPathParam("connection_id", connectionId)
      .withSuccessResponse[Unit](200)
      

  /**
   * Expected answers:
   *   code 200 : Seq[SyncLog] (Sync logs)
   * 
   * Available security schemes:
   *   bearer_token (http)
   * 
   * @param connectionId 
   */
  def getSyncLogsApi(connectionId: String)(implicit bearerToken: BearerToken): ApiRequest[Seq[SyncLog]] =
    ApiRequest[Seq[SyncLog]](ApiMethods.GET, baseUrl, "/api/v1/marketplace/connections/{connection_id}/logs", "application/json")
      .withCredentials(bearerToken).withPathParam("connection_id", connectionId)
      .withSuccessResponse[Seq[SyncLog]](200)
      

  /**
   * Expected answers:
   *   code 200 : Seq[MarketplaceConnection] (List of connections)
   * 
   * Available security schemes:
   *   bearer_token (http)
   */
  def listConnectionsApi()(implicit bearerToken: BearerToken): ApiRequest[Seq[MarketplaceConnection]] =
    ApiRequest[Seq[MarketplaceConnection]](ApiMethods.GET, baseUrl, "/api/v1/marketplace/connections", "application/json")
      .withCredentials(bearerToken).withSuccessResponse[Seq[MarketplaceConnection]](200)
      

  /**
   * Expected answers:
   *   code 200 : Seq[PlatformInfo] (Supported platforms)
   * 
   * Available security schemes:
   *   bearer_token (http)
   */
  def listPlatformsApi()(implicit bearerToken: BearerToken): ApiRequest[Seq[PlatformInfo]] =
    ApiRequest[Seq[PlatformInfo]](ApiMethods.GET, baseUrl, "/api/v1/marketplace/platforms", "application/json")
      .withCredentials(bearerToken).withSuccessResponse[Seq[PlatformInfo]](200)
      

  /**
   * Expected answers:
   *   code 200 : OAuthAuthorizeResponse (Authorization URL)
   * 
   * Available security schemes:
   *   bearer_token (http)
   * 
   * @param oAuthAuthorizeRequest 
   */
  def oauthAuthorizeApi(oAuthAuthorizeRequest: OAuthAuthorizeRequest)(implicit bearerToken: BearerToken): ApiRequest[OAuthAuthorizeResponse] =
    ApiRequest[OAuthAuthorizeResponse](ApiMethods.POST, baseUrl, "/api/v1/marketplace/oauth/authorize", "application/json")
      .withCredentials(bearerToken).withBody(oAuthAuthorizeRequest)
      .withSuccessResponse[OAuthAuthorizeResponse](200)
      

  /**
   * Expected answers:
   *   code 200 : MarketplaceConnection (Connection created/updated)
   * 
   * Available security schemes:
   *   bearer_token (http)
   * 
   * @param oAuthCallbackRequest 
   */
  def oauthCallbackApi(oAuthCallbackRequest: OAuthCallbackRequest)(implicit bearerToken: BearerToken): ApiRequest[MarketplaceConnection] =
    ApiRequest[MarketplaceConnection](ApiMethods.POST, baseUrl, "/api/v1/marketplace/oauth/callback", "application/json")
      .withCredentials(bearerToken).withBody(oAuthCallbackRequest)
      .withSuccessResponse[MarketplaceConnection](200)
      

  /**
   * Expected answers:
   *   code 200 : SyncSummary (Sync triggered)
   * 
   * Available security schemes:
   *   bearer_token (http)
   * 
   * @param connectionId 
   * @param syncType 
   * @param direction 
   */
  def triggerSyncApi(connectionId: String, syncType: Option[String] = None, direction: Option[String] = None)(implicit bearerToken: BearerToken): ApiRequest[SyncSummary] =
    ApiRequest[SyncSummary](ApiMethods.POST, baseUrl, "/api/v1/marketplace/connections/{connection_id}/sync", "application/json")
      .withCredentials(bearerToken).withQueryParam("sync_type", syncType)
      .withQueryParam("direction", direction)
      .withPathParam("connection_id", connectionId)
      .withSuccessResponse[SyncSummary](200)
      

  /**
   * Expected answers:
   *   code 200 : MarketplaceConnection (Updated)
   * 
   * Available security schemes:
   *   bearer_token (http)
   * 
   * @param connectionId 
   * @param updateConnectionRequest 
   */
  def updateConnectionApi(connectionId: String, updateConnectionRequest: UpdateConnectionRequest)(implicit bearerToken: BearerToken): ApiRequest[MarketplaceConnection] =
    ApiRequest[MarketplaceConnection](ApiMethods.PUT, baseUrl, "/api/v1/marketplace/connections/{connection_id}", "application/json")
      .withCredentials(bearerToken).withBody(updateConnectionRequest)
      .withPathParam("connection_id", connectionId)
      .withSuccessResponse[MarketplaceConnection](200)
      

  /**
   * Expected answers:
   *   code 200 :  (Sync directions updated)
   * 
   * Available security schemes:
   *   bearer_token (http)
   * 
   * @param connectionId 
   * @param updateSyncDirectionRequest 
   */
  def updateSyncDirectionApi(connectionId: String, updateSyncDirectionRequest: UpdateSyncDirectionRequest)(implicit bearerToken: BearerToken): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.PUT, baseUrl, "/api/v1/marketplace/connections/{connection_id}/directions", "application/json")
      .withCredentials(bearerToken).withBody(updateSyncDirectionRequest)
      .withPathParam("connection_id", connectionId)
      .withSuccessResponse[Unit](200)
      

  /**
   * Expected answers:
   *   code 200 :  (Webhook received)
   *   code 401 :  (Invalid signature)
   * 
   * Available security schemes:
   *   bearer_token (http)
   * 
   * @param platform 
   * @param connectionId 
   */
  def webhookReceiverApi(platform: String, connectionId: String)(implicit bearerToken: BearerToken): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.POST, baseUrl, "/api/v1/marketplace/webhook/{platform}/{connection_id}", "application/json")
      .withCredentials(bearerToken).withPathParam("platform", platform)
      .withPathParam("connection_id", connectionId)
      .withSuccessResponse[Unit](200)
      .withErrorResponse[Unit](401)
      



}

