/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.api

import org.openapitools.client.model.AnyType
import org.openapitools.client.model.PayrollCreatePayload
import org.openapitools.client.model.PayrollPayPayload
import org.openapitools.client.model.PayrollRunApi
import java.util.UUID
import org.openapitools.client.model.YearlyPayrollSummary
import org.openapitools.client.core._
import org.openapitools.client.core.CollectionFormats._
import org.openapitools.client.core.ApiKeyLocations._

object PayrollApi {

  def apply(baseUrl: String = "https://demo.simplebilly.com") = new PayrollApi(baseUrl)
}

class PayrollApi(baseUrl: String) {

  /**
   * Expected answers:
   *   code 200 : PayrollRunApi ()
   * 
   * Available security schemes:
   *   bearer_token (http)
   * 
   * @param id 
   */
  def payrollApprove(id: UUID)(implicit bearerToken: BearerToken): ApiRequest[PayrollRunApi] =
    ApiRequest[PayrollRunApi](ApiMethods.POST, baseUrl, "/api/v1/payroll/{id}/approve", "application/json")
      .withCredentials(bearerToken).withPathParam("id", id)
      .withSuccessResponse[PayrollRunApi](200)
      

  /**
   * Expected answers:
   *   code 200 : AnyType ()
   * 
   * Available security schemes:
   *   bearer_token (http)
   * 
   * @param id 
   * @param body 
   */
  def payrollAutopay(id: String, body: Option[AnyType] = None)(implicit bearerToken: BearerToken): ApiRequest[AnyType] =
    ApiRequest[AnyType](ApiMethods.POST, baseUrl, "/api/v1/payroll/{id}/autopay", "application/json")
      .withCredentials(bearerToken).withBody(body)
      .withPathParam("id", id)
      .withSuccessResponse[AnyType](200)
      

  /**
   * Expected answers:
   *   code 200 : PayrollRunApi ()
   * 
   * Available security schemes:
   *   bearer_token (http)
   * 
   * @param id 
   */
  def payrollCalculate(id: UUID)(implicit bearerToken: BearerToken): ApiRequest[PayrollRunApi] =
    ApiRequest[PayrollRunApi](ApiMethods.POST, baseUrl, "/api/v1/payroll/{id}/calculate", "application/json")
      .withCredentials(bearerToken).withPathParam("id", id)
      .withSuccessResponse[PayrollRunApi](200)
      

  /**
   * Expected answers:
   *   code 201 : PayrollRunApi ()
   * 
   * Available security schemes:
   *   bearer_token (http)
   * 
   * @param payrollCreatePayload 
   */
  def payrollCreate(payrollCreatePayload: PayrollCreatePayload)(implicit bearerToken: BearerToken): ApiRequest[PayrollRunApi] =
    ApiRequest[PayrollRunApi](ApiMethods.POST, baseUrl, "/api/v1/payroll", "application/json")
      .withCredentials(bearerToken).withBody(payrollCreatePayload)
      .withSuccessResponse[PayrollRunApi](201)
      

  /**
   * Expected answers:
   *   code 204 :  (No Content)
   * 
   * Available security schemes:
   *   bearer_token (http)
   * 
   * @param id 
   */
  def payrollDelete(id: UUID)(implicit bearerToken: BearerToken): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.DELETE, baseUrl, "/api/v1/payroll/{id}", "application/json")
      .withCredentials(bearerToken).withPathParam("id", id)
      .withSuccessResponse[Unit](204)
      

  /**
   * Expected answers:
   *   code 200 :  (CSV export)
   * 
   * Available security schemes:
   *   bearer_token (http)
   * 
   * @param id 
   */
  def payrollElsterExport(id: UUID)(implicit bearerToken: BearerToken): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.POST, baseUrl, "/api/v1/payroll/{id}/elster-export", "application/json")
      .withCredentials(bearerToken).withPathParam("id", id)
      .withSuccessResponse[Unit](200)
      

  /**
   * Expected answers:
   *   code 200 : AnyType ()
   * 
   * Available security schemes:
   *   bearer_token (http)
   * 
   * @param id 
   */
  def payrollEmail(id: String)(implicit bearerToken: BearerToken): ApiRequest[AnyType] =
    ApiRequest[AnyType](ApiMethods.POST, baseUrl, "/api/v1/payroll/{id}/email", "application/json")
      .withCredentials(bearerToken).withPathParam("id", id)
      .withSuccessResponse[AnyType](200)
      

  /**
   * Expected answers:
   *   code 200 :  (PDF slip)
   * 
   * Available security schemes:
   *   bearer_token (http)
   * 
   * @param id 
   * @param entryId 
   */
  def payrollEntryPdf(id: String, entryId: String)(implicit bearerToken: BearerToken): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.GET, baseUrl, "/api/v1/payroll/{id}/entries/{entry_id}/pdf", "application/json")
      .withCredentials(bearerToken).withPathParam("id", id)
      .withPathParam("entry_id", entryId)
      .withSuccessResponse[Unit](200)
      

  /**
   * Expected answers:
   *   code 200 : PayrollRunApi ()
   * 
   * Available security schemes:
   *   bearer_token (http)
   * 
   * @param id 
   */
  def payrollGet(id: UUID)(implicit bearerToken: BearerToken): ApiRequest[PayrollRunApi] =
    ApiRequest[PayrollRunApi](ApiMethods.GET, baseUrl, "/api/v1/payroll/{id}", "application/json")
      .withCredentials(bearerToken).withPathParam("id", id)
      .withSuccessResponse[PayrollRunApi](200)
      

  /**
   * Expected answers:
   *   code 200 : Seq[PayrollRunApi] ()
   * 
   * Available security schemes:
   *   bearer_token (http)
   * 
   * @param year 
   * @param status 
   */
  def payrollList(year: Option[Int] = None, status: Option[String] = None)(implicit bearerToken: BearerToken): ApiRequest[Seq[PayrollRunApi]] =
    ApiRequest[Seq[PayrollRunApi]](ApiMethods.GET, baseUrl, "/api/v1/payroll", "application/json")
      .withCredentials(bearerToken).withQueryParam("year", year)
      .withQueryParam("status", status)
      .withSuccessResponse[Seq[PayrollRunApi]](200)
      

  /**
   * Expected answers:
   *   code 200 : PayrollRunApi ()
   * 
   * Available security schemes:
   *   bearer_token (http)
   * 
   * @param id 
   * @param payrollPayPayload 
   */
  def payrollPay(id: UUID, payrollPayPayload: PayrollPayPayload)(implicit bearerToken: BearerToken): ApiRequest[PayrollRunApi] =
    ApiRequest[PayrollRunApi](ApiMethods.POST, baseUrl, "/api/v1/payroll/{id}/pay", "application/json")
      .withCredentials(bearerToken).withBody(payrollPayPayload)
      .withPathParam("id", id)
      .withSuccessResponse[PayrollRunApi](200)
      

  /**
   * Expected answers:
   *   code 200 :  (PDF summary)
   * 
   * Available security schemes:
   *   bearer_token (http)
   * 
   * @param id 
   */
  def payrollPdf(id: String)(implicit bearerToken: BearerToken): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.GET, baseUrl, "/api/v1/payroll/{id}/pdf", "application/json")
      .withCredentials(bearerToken).withPathParam("id", id)
      .withSuccessResponse[Unit](200)
      

  /**
   * Expected answers:
   *   code 200 : YearlyPayrollSummary ()
   * 
   * Available security schemes:
   *   bearer_token (http)
   * 
   * @param year 
   */
  def payrollSummary(year: Int)(implicit bearerToken: BearerToken): ApiRequest[YearlyPayrollSummary] =
    ApiRequest[YearlyPayrollSummary](ApiMethods.GET, baseUrl, "/api/v1/payroll/summary/{year}", "application/json")
      .withCredentials(bearerToken).withPathParam("year", year)
      .withSuccessResponse[YearlyPayrollSummary](200)
      

  /**
   * Expected answers:
   *   code 200 : AnyType ()
   * 
   * Available security schemes:
   *   bearer_token (http)
   * 
   * @param id 
   */
  def payrollSvMeldungen(id: UUID)(implicit bearerToken: BearerToken): ApiRequest[AnyType] =
    ApiRequest[AnyType](ApiMethods.POST, baseUrl, "/api/v1/payroll/{id}/sv-meldungen", "application/json")
      .withCredentials(bearerToken).withPathParam("id", id)
      .withSuccessResponse[AnyType](200)
      



}

